version: 0.2

env:
  variables:
    AWS_REGION: "ca-central-1"
    ECR_REPO: "111376855663.dkr.ecr.ca-central-1.amazonaws.com/nodejs-app"
    CLUSTER_NAME: "nodejs-app-cluster"
    SERVICE_NAME: "nodejs-app-service"
    TASK_FAMILY: "nodejs-app-task"
    CONTAINER_NAME: "nodejs-app"
    CONTAINER_PORT: "3000"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y jq aws-cli docker

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 111376855663.dkr.ecr.ca-central-1.amazonaws.com

  build:
    commands:
      - echo "Preparing ECS deployment..."
      - IMAGE_URI="$ECR_REPO:latest"
      - echo "Using image: $IMAGE_URI"

      # 1. Create ECS cluster if it doesn’t exist
      - |
        if ! aws ecs describe-clusters --clusters $CLUSTER_NAME --region $AWS_REGION | grep -q "ACTIVE"; then
          echo "Creating ECS cluster: $CLUSTER_NAME"
          aws ecs create-cluster --cluster-name $CLUSTER_NAME --region $AWS_REGION
        else
          echo "ECS cluster already exists: $CLUSTER_NAME"
        fi

      # 2. Register ECS task definition using LabRole
      - |
        echo "Registering new ECS task definition using LabRole..."
        cat <<EOF > taskdef.json
        {
          "family": "$TASK_FAMILY",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "256",
          "memory": "512",
          "executionRoleArn": "arn:aws:iam::111376855663:role/LabRole",
          "taskRoleArn": "arn:aws:iam::111376855663:role/LabRole",
          "containerDefinitions": [
            {
              "name": "$CONTAINER_NAME",
              "image": "$IMAGE_URI",
              "essential": true,
              "portMappings": [
                {
                  "containerPort": $CONTAINER_PORT,
                  "protocol": "tcp"
                }
              ],
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-group": "/ecs/$TASK_FAMILY",
                  "awslogs-region": "$AWS_REGION",
                  "awslogs-stream-prefix": "ecs"
                }
              }
            }
          ]
        }
        EOF
        aws ecs register-task-definition --cli-input-json file://taskdef.json

      # 3. Create or update ECS service
      - |
        if ! aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --region $AWS_REGION | grep -q "ACTIVE"; then
          echo "Creating ECS service: $SERVICE_NAME"
          aws ecs create-service \
            --cluster $CLUSTER_NAME \
            --service-name $SERVICE_NAME \
            --task-definition $TASK_FAMILY \
            --desired-count 1 \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-xxxxxxx,subnet-yyyyyyy],securityGroups=[sg-xxxxxxx],assignPublicIp=ENABLED}"
        else
          echo "Updating ECS service with new task definition..."
          NEW_TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_FAMILY | jq -r '.taskDefinition.taskDefinitionArn')
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --task-definition $NEW_TASK_DEF
        fi

  post_build:
    commands:
      - echo "ECS deployment complete."
